env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules:
  array-bracket-spacing:
    - error
    - never
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-undef: 0
  no-trailing-spaces:
    - error
    - ignoreComments: true
      skipBlankLines: true
  semi:
    - error
    - always
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - last
  vue/component-name-in-template-casing:
    - error
    - kebab-case
  vue/html-end-tags: error
  vue/html-self-closing: 0
  vue/no-v-model-argument: 0
  vue/no-v-html: 0
  vue/multi-word-component-names: 0
  vue/max-attributes-per-line:
    - error
    - singleline: 6
      multiline: 6
  vue/singleline-html-element-content-newline: 0
  vue/no-deprecated-events-api: 0
