name: Build assets

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

  workflow_run:
    workflows: [PHP linting (Pint), Javascript linting]
    types: [completed]
    branches-ignore: [main]

env:
  node-version: 18

concurrency:
  group: Build assets ${{ github.ref }}
  cancel-in-progress: true


jobs:
  #############
  # Build
  #############
  build:
    runs-on: ubuntu-latest
    name: Build Assets

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache yarn files
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Build assets
        run: yarn run build
