name: Docker

on:
  push:
    branches:
      - main

concurrency:
  group: Docker ${{ github.ref }}
  cancel-in-progress: true

env:
  package-name: monica-next

jobs:
  docker-run:
    runs-on: ubuntu-latest
    name: Docker build developpment

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.package-name }}
          tag-sha: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

    # Configure
      - name: Configure variables
        run: scripts/docker/build.sh --skip-build $GITHUB_SHA

    # Build docker
      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ env.package-name }}:main
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: scripts/docker/Dockerfile
          context: .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Prune images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.CR_PAT }}
          organization: ${{ github.repository_owner }}
          container: ${{ env.package-name }}
          keep-younger-than: 15
          prune-untagged: true
