name: Code Linters

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_run:
    workflows: [Code Linters]
    types: [completed]

jobs:
  phplint:
    runs-on: ubuntu-latest
    name: PHP linting (Pint)

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        if: env.GH_TOKEN != ''
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v3
        if: env.GH_TOKEN == ''
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: laravel-pint
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel

      - name: Commit changes
        if: env.GH_TOKEN != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: php linting with pint'
          skip_fetch: true

      - name: Check if there is any file update needed
        if: env.GH_TOKEN == ''
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "Waiting modifications:\n$status"
            echo "::error::Laravel pint found fixes. Please run 'vendor/bin/pint' prior to your next commit."
            exit -1
          fi

  eslint:
    runs-on: ubuntu-latest
    name: Lint vue and js files

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        if: env.GH_TOKEN != ''
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v3
        if: env.GH_TOKEN == ''
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn files
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-yarn-

      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Run eslint
        run: yarn run lint --fix
      - name: Run prettier
        run: yarn run format

      - name: Commit changes
        if: env.GH_TOKEN != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: javascript linting with eslint and prettier'
          skip_fetch: true

      - name: Check if there is any file update needed
        if: env.GH_TOKEN == ''
        run: |
          status=$(git status --porcelain)
          if [ -n "$status" ]; then
            echo -e "Waiting modifications:\n$status"
            echo "::error::Eslint and prettier found fixes. Please run 'yarn run lint' and 'yarn run format' prior to your next commit."
            exit -1
          fi
